<?php

declare(strict_types=1);

namespace Gingerminds\LaravelCms\Blocks\Type;

use Gingerminds\LaravelCms\Blocks\AbstractBlock;

/**
 * Block Image block, generated by `make:cms-block` (see docs/Blocks.md).
 * Auto-discovered from `app/Cms/Blocks` — no manual registration needed.
 */
class TextImage extends AbstractBlock
{
    /**
     * Stable identifier, used as `type` in PageTranslation::content and as
     * the registry key. Never change once a page uses this block.
     */
    public function key(): string
    {
        return 'text_image';
    }

    /** Label shown in the block picker (add-block modal, step 1). */
    public function label(): string
    {
        return __('gingerminds-cms::translation.blocks.text_image.label');
    }

    /** Bootstrap Icons class shown next to the label in the picker. */
    public function icon(): string
    {
        return 'bi-image';
    }

    public function order(): int
    {
        return 100;
    }

    /**
     * Declarative field schema — see BlockInterface::fields() for the full
     * set of supported keys (type, size, rules, options, preset/rows for
     * wysiwyg...). Replace this example with the block's real fields.
     *
     * @return array<int, array<string, mixed>>
     */
    public function fields(): array
    {
        return [
            [
                'name' => 'image_position',
                'type' => 'toggle',
                'label' => __('gingerminds-cms::translation.blocks.text_image.fields.image_position'),
                'required' => false,
                'helper' => __('gingerminds-cms::translation.blocks.text_image.fields.image_position_helper'),
            ],
            [
                'name' => 'title',
                'type' => 'text',
                'label' => __('gingerminds-cms::translation.blocks.text_image.fields.title'),
                'required' => true,
                'size' => 'md',
            ],
            [
                'name' => 'text',
                'type' => 'wysiwyg',
                'label' => __('gingerminds-cms::translation.blocks.text_image.fields.text'),
                'required' => false,
                'size' => 'xl',
                'preset' => 'default',
                'rows' => 8,
            ],
            [
                'name' => 'image',
                'type' => 'file',
                'label' => __('gingerminds-cms::translation.blocks.text_image.fields.image'),
                'required' => true,
                'size' => 'xl',
            ],
        ];
    }

    public function previewView(): string
    {
        return 'gingerminds-cms::blocks.type.text-image.preview';
    }
}
